package app.bookreader.core.format

/** Human-readable Russian names for FB2 genre codes, the ones Flibusta and most libraries use. */
object Fb2Genres {
    private val names = mapOf(
        "sf" to "Научная фантастика",
        "sf_history" to "Альтернативная история",
        "sf_action" to "Боевая фантастика",
        "sf_epic" to "Эпическая фантастика",
        "sf_heroic" to "Героическая фантастика",
        "sf_detective" to "Детективная фантастика",
        "sf_cyberpunk" to "Киберпанк",
        "sf_space" to "Космическая фантастика",
        "sf_social" to "Социальная фантастика",
        "sf_horror" to "Ужасы и мистика",
        "sf_humor" to "Юмористическая фантастика",
        "sf_fantasy" to "Фэнтези",
        "sf_fantasy_city" to "Городское фэнтези",
        "sf_postapocalyptic" to "Постапокалипсис",
        "sf_litrpg" to "ЛитРПГ",
        "popadanec" to "Попаданцы",
        "det_classic" to "Классический детектив",
        "det_police" to "Полицейский детектив",
        "det_action" to "Боевик",
        "det_irony" to "Иронический детектив",
        "det_history" to "Исторический детектив",
        "det_espionage" to "Шпионский детектив",
        "det_crime" to "Криминальный детектив",
        "det_political" to "Политический детектив",
        "det_maniac" to "Маньяки",
        "det_hard" to "Крутой детектив",
        "detective" to "Детектив",
        "thriller" to "Триллер",
        "prose_classic" to "Классическая проза",
        "prose_history" to "Историческая проза",
        "prose_contemporary" to "Современная проза",
        "prose_counter" to "Контркультура",
        "prose_rus_classic" to "Русская классическая проза",
        "prose_su_classics" to "Советская классическая проза",
        "prose_military" to "Военная проза",
        "prose" to "Проза",
        "love_contemporary" to "Современные любовные романы",
        "love_history" to "Исторические любовные романы",
        "love_detective" to "Остросюжетные любовные романы",
        "love_short" to "Короткие любовные романы",
        "love_erotica" to "Эротика",
        "love_sf" to "Любовное фэнтези",
        "love" to "Любовные романы",
        "adv_western" to "Вестерн",
        "adv_history" to "Исторические приключения",
        "adv_indian" to "Приключения про индейцев",
        "adv_maritime" to "Морские приключения",
        "adv_geo" to "Путешествия и география",
        "adv_animal" to "Природа и животные",
        "adventure" to "Приключения",
        "child_tale" to "Сказки",
        "child_verse" to "Детские стихи",
        "child_prose" to "Детская проза",
        "child_sf" to "Детская фантастика",
        "child_det" to "Детские остросюжетные",
        "child_adv" to "Детские приключения",
        "child_education" to "Детская образовательная литература",
        "children" to "Детская литература",
        "poetry" to "Поэзия",
        "dramaturgy" to "Драматургия",
        "antique_ant" to "Античная литература",
        "antique_european" to "Европейская старинная литература",
        "antique_russian" to "Древнерусская литература",
        "antique_east" to "Древневосточная литература",
        "antique_myths" to "Мифы, легенды, эпос",
        "antique" to "Старинная литература",
        "sci_history" to "История",
        "sci_psychology" to "Психология",
        "sci_culture" to "Культурология",
        "sci_religion" to "Религиоведение",
        "sci_philosophy" to "Философия",
        "sci_politics" to "Политика",
        "sci_business" to "Деловая литература",
        "sci_juris" to "Юриспруденция",
        "sci_linguistic" to "Языкознание",
        "sci_medicine" to "Медицина",
        "sci_phys" to "Физика",
        "sci_math" to "Математика",
        "sci_chem" to "Химия",
        "sci_biology" to "Биология",
        "sci_tech" to "Технические науки",
        "sci_popular" to "Научно-популярное",
        "science" to "Научная литература",
        "comp_www" to "Интернет",
        "comp_programming" to "Программирование",
        "comp_hard" to "Компьютерное железо",
        "comp_soft" to "Программы",
        "comp_db" to "Базы данных",
        "comp_osnet" to "ОС и сети",
        "computers" to "Компьютерная литература",
        "ref_encyc" to "Энциклопедии",
        "ref_dict" to "Словари",
        "ref_ref" to "Справочники",
        "ref_guide" to "Руководства",
        "reference" to "Справочная литература",
        "nonf_biography" to "Биографии и мемуары",
        "nonf_publicism" to "Публицистика",
        "nonf_criticism" to "Критика",
        "design" to "Искусство и дизайн",
        "nonfiction" to "Документальная литература",
        "religion_rel" to "Религия",
        "religion_esoterics" to "Эзотерика",
        "religion_self" to "Самосовершенствование",
        "religion" to "Религия и духовность",
        "humor_anecdote" to "Анекдоты",
        "humor_prose" to "Юмористическая проза",
        "humor_verse" to "Юмористические стихи",
        "humor" to "Юмор",
        "home_cooking" to "Кулинария",
        "home_pets" to "Домашние животные",
        "home_crafts" to "Хобби и ремёсла",
        "home_entertain" to "Развлечения",
        "home_health" to "Здоровье",
        "home_garden" to "Сад и огород",
        "home_diy" to "Сделай сам",
        "home_sport" to "Спорт",
        "home_sex" to "Эротика, секс",
        "home" to "Дом и семья",
    )

    /** "sf_fantasy" → "Фэнтези". Unknown codes and free-text EPUB subjects pass through unchanged. */
    fun displayName(code: String): String = names[code.trim().lowercase()] ?: code.trim()
}
